export const buildCodexSchemaReference = (): string => {
  return [
    '# codex_schema_reference.md',
    '',
    '## Canonical VN structures',
    '- `RouteDefinition`: Route identity, unlock conditions, reveal policy, enabled state.',
    '- `RevealPlan`: Which information keys can be revealed in which routes/scenes.',
    '- `StateAxis`: Typed state registry (`number`, `boolean`, `string`) with scope/defaults.',
    '- `BranchPolicy`: Branch level and convergence requirements for target patterns.',
    '- `ScenePackage`: Canonical scene design unit (spine, choices, variants, convergence).',
    '- `ChoicePoint`: Player choice + condition/effect metadata + variant/convergence targets.',
    '- `ReactionVariant`: Variant response blocks with state/reveal effects and convergence policy.',
    '- `ConvergencePoint`: How a branching scene merges into target block/policy.',
    '',
    '## Canonical vs cached fields',
    '- Canonical: `bible.routes`, `bible.revealPlans`, `bible.stateAxes`, `bible.branchPolicies`, `chapter.scenePackages`.',
    '- Cached/display-only: `chapter.content`.',
    '- `chapter.scenePackages` are upstream of draft text; update scene packages first, then rebuild draft/content.',
    '',
    '## Condition fields and type safety',
    '- `ScenePackage.entryConditions`: scene entry gate. If false, the package is skipped or replaced by fallback flow.',
    '- `ChoicePoint.visibilityCondition`: whether a choice is shown to the player.',
    '- `ChoicePoint.availabilityCondition`: whether a visible choice is currently selectable.',
    '- All condition fields must reference declared `StateAxis.key` values only.',
    '- Condition value types must match axis type (`number`/`boolean`/`string`) and operator semantics.',
    '',
    '## Choice impact fields',
    '- `ChoicePoint.routeImpact`: route progression/priority/lock influence caused by the choice.',
    '- `ChoicePoint.unlockImpact`: unlock side-effects for routes/scenes/flags used later.',
    '- `immediateEffects`, `delayedEffects`, and `carryoverStateChanges` should not conflict in meaning.',
    '',
    '## Carryover and convergence semantics',
    '- `ScenePackage.carryoverStateChanges`: persistent state changes that cross scene/chapter boundaries.',
    '- Divergent choices should provide explicit convergence via `ChoicePoint.convergenceTarget` and/or `ScenePackage.convergencePoint`.',
    '- `ConvergencePoint.convergencePolicy` and `ReactionVariant.convergencePolicy` must remain compatible.',
    '',
    '## Variant/reference integrity checks',
    '- Every `ChoicePoint.reactionVariantId` / `immediateReactionVariantId` must resolve to a variant in the same scene package.',
    '- Variant IDs and convergence targets should stay stable unless create/delete is intentional and reflected everywhere.',
    '',
    '## Codex editing rules',
    '- Keep IDs stable unless intentionally creating/deleting entities.',
    '- Preserve type consistency between condition expressions and `StateAxis` definitions.',
    '- Prefer scope-limited edits (scene/chapter) instead of project-wide prose rewrites.',
    '- Report unresolved validator issues explicitly instead of silently dropping branch structures.',
  ].join('\n');
};
