export const buildCodexSchemaReference = (): string => {
  return [
    '# codex_schema_reference.md',
    '',
    '## Canonical VN structures',
    '- `RouteDefinition`: Route identity, unlock conditions, reveal policy, enabled state.',
    '- `RevealPlan`: Which information keys can be revealed in which routes/scenes.',
    '- `StateAxis`: Typed state registry (`number`, `boolean`, `string`) with scope/defaults.',
    '- `BranchPolicy`: Branch level and convergence requirements for target patterns.',
    '- `ScenePackage`: Canonical scene design unit (spine, choices, variants, convergence).',
    '- `ChoicePoint`: Player choice + condition/effect metadata + variant/convergence targets.',
    '- `ReactionVariant`: Variant response blocks with state/reveal effects and convergence policy.',
    '- `ConvergencePoint`: How a branching scene merges into target block/policy.',
    '',
    '## Source-of-truth rules',
    '- Canonical: `bible.routes`, `bible.revealPlans`, `bible.stateAxes`, `bible.branchPolicies`, `chapter.scenePackages`.',
    '- Cached/display-only: `chapter.content`.',
    '- `chapter.scenePackages` are upstream of draft text; chapter prose should be rebuilt from scene packages after branch edits.',
    '',
    '## Conditions & type safety',
    '- `ScenePackage.entryConditions`, `ChoicePoint.visibilityCondition`, and `ChoicePoint.availabilityCondition` must reference declared `StateAxis.key` values.',
    '- Condition value types must match axis type (`number`/`boolean`/`string`) and supported operators.',
    '- Do not introduce unknown state keys in conditions or effects.',
    '',
    '## Choice and branch impacts',
    '- `ChoicePoint.routeImpact`: how the choice nudges route progression or route lock state.',
    '- `ChoicePoint.unlockImpact`: unlock side-effects for routes/scenes/flags used later.',
    '- `immediateEffects`, `delayedEffects`, and `carryoverStateChanges` should stay semantically consistent.',
    '',
    '## Carryover and convergence semantics',
    '- `ScenePackage.carryoverStateChanges` describes state that must persist to subsequent scenes/chapters.',
    '- If choices diverge, provide explicit convergence via `ChoicePoint.convergenceTarget` and/or `ScenePackage.convergencePoint`.',
    '- `ConvergencePoint.convergencePolicy` and `ReactionVariant.convergencePolicy` should not conflict.',
    '',
    '## Codex editing rules',
    '- Keep IDs stable unless intentionally creating/deleting entities.',
    '- Preserve type consistency between condition expressions and `StateAxis` definitions.',
    '- Every `ChoicePoint.reactionVariantId` / `immediateReactionVariantId` should resolve to an existing variant in the same scene package.',
    '- Report unresolved validator issues explicitly instead of silently dropping branch structures.',
  ].join('\n');
};
